"""Generated-code detection (header markers) in :mod:`bounds.ignore`.

The marker set must catch the common compiled-language generated headers (Go protobuf's
``protoc-gen-go`` banner and friends) so a generated compiled file is recognized as generated and
excluded from coverage — while a normal source file is never misdetected (the head-only scan window
is the false-positive guard, deliberately not widened).
"""

from __future__ import annotations

from bounds.shared.ignore import has_generated_marker, is_generated


def test_protobuf_go_header_is_generated():
    """The canonical Go protobuf banner (``// Code generated by protoc-gen-go. DO NOT EDIT.``) is
    recognized as generated via both the ``code generated by`` and ``do not edit`` markers."""
    src = b"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage payments\n"
    assert has_generated_marker(src) is True
    assert is_generated("services/payments/charge.pb.go", src, []) is True


def test_do_not_edit_banner_is_generated():
    """A bare ``DO NOT EDIT`` banner (Thrift/SWIG/codegen tools) is recognized, case-insensitively."""
    assert has_generated_marker(b"/* AUTO-FILE. do not edit by hand. */\nfunc x() {}\n") is True


def test_legacy_at_generated_marker_still_detected():
    """The original decorator-style markers keep working (no regression)."""
    assert has_generated_marker(b"// @generated\npackage x\n") is True
    assert has_generated_marker(b"# auto-generated file\nx = 1\n") is True


def test_normal_source_file_is_not_generated():
    """An ordinary hand-written source file carries no marker and is never flagged generated."""
    assert has_generated_marker(b"package payments\nfunc Charge() error { return nil }\n") is False
    assert is_generated("services/payments/charge.go",
                        b"package payments\nfunc Charge() error { return nil }\n", []) is False


def test_marker_deep_in_body_does_not_trip():
    """Head-only scan (the false-positive guard): a ``do not edit`` mention far past the header
    window must NOT mark the file generated."""
    src = b"package x\n" + b"// real code\n" * 1000 + b"// do not edit this function\n"
    assert has_generated_marker(src) is False
