"""Cross-agent protocol: teach coding agents to read architecture via the CLI.

The problem this solves: AI coding agents (Claude Code, Cursor, Copilot, Gemini, …) each
have their own out-of-band convention for project instructions, and when left to their own
devices they may read the raw `.bounds/` files — the binary cache and the unverified YAML
manifests — which both defeats tree-sitter verification *and* burns context on data the CLI
already compresses.

This module writes a single canonical contract in ``AGENTS.md`` — the cross-ecosystem
standard file that agents already read — plus a small per-agent *pointer* file in each
agent's native config location, all conveying the same essentials: use ``bounds list`` /
``bounds describe`` / ``bounds validate --quick`` to read architecture, never read raw
``.bounds`` artifacts, and treat the CLI as the API. ``AGENTS.md`` is the source of truth; every per-tool pointer references it, so
there is exactly one place the contract lives.

Design constraints (enforced repo-wide):
  * Pure stdlib, no new dependencies.
  * These are *generated artifacts*, not structural JSON. Each managed block is wrapped in
    ``<!-- BOUNDS:START -->`` / ``<!-- BOUNDS:END -->`` markers and stamped with the bounds
    version + an 8-char content hash. That stamp is the ONLY non-deterministic element and it
    is confined to these agent-config files — it never reaches any ``describe`` / ``validate``
    / ``list`` JSON, nor any cache/validation hash. Everything *around* a managed block (and
    the body apart from the stamp) is deterministic, so a re-sync of unedited files is a no-op.
  * Fail soft: the only fatal condition is genuine misuse (bad ``mode`` / bad agent key),
    which raises ``BoundsError(E_USAGE)``. A *shared* config a human wrote — one with no markers
    but mentioning bounds, or with markers whose body a human edited — is never clobbered; it is
    reported (``skipped_custom``) and left untouched. A *dedicated* (bounds-only) file is ours to
    keep current: a legacy unmarked one is migrated to a stamped block and deleted front-matter
    is restored.

The three modes:
  * ``sync``   — write ``AGENTS.md`` and the selected agents' pointer files; return what changed.
  * ``detect`` — heuristically report which agents' tool footprints are present.
  * ``check``  — for detected agents, report which have a stale/missing bounds config.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

from . import config, errors
from .manifest import loader as manifest_loader

__all__ = ["run_agent"]

# ---------------------------------------------------------------------------
# Canonical contract content (committed in AGENTS.md; the single source of truth)
# ---------------------------------------------------------------------------
CANONICAL_NAME = "AGENTS.md"

# AGENTS.md is GENERATED by `bounds agent --sync` from CANONICAL_BODY below — the committed file
# is just its rendered output. Make any contract change (including the Source of Truth / staleness
# block) HERE and regenerate with `bounds agent --sync`; edits made directly to AGENTS.md are
# overwritten on the next sync.
#
# The full contract. Lives inside AGENTS.md's marked block so it coexists with any other
# AGENTS.md content a project already keeps. The leading warning line is intentional: it tells
# a human reader (and any agent) that the block is machine-managed.
CANONICAL_BODY = f"""\
> Managed by `bounds agent --sync` — edits inside this block are overwritten; edit the generator (`src/bounds/agentsync.py`) instead.

## Bounds — architecture contract for agents

Bounds models this codebase as subsystem boundary manifests. Query architecture through the CLI — never read raw `.bounds` files.

### Which command for which task
- Understand the layout / find the right subsystem → `bounds list`
- A subsystem's public surface or DB tables → `bounds describe <name>` (a few hundred tokens, tree-sitter-verified — use this before opening source or migrations)
- Every subsystem in a namespace → `bounds describe --namespace <ns>`
- Where a symbol or table is defined → `bounds where <symbol>`
- What breaks if you change a subsystem or table → `bounds impact <name>`
- Confirm an edit didn't drift the contract → `bounds validate --quick`
- Project health, coverage, and trust guidance → `bounds overview`

### Workflow
1. `bounds list` before broad repo search.
2. `bounds describe <name>` to scope the contract, then read only the implementation files you need to edit.
3. `bounds impact <name>` before changing an interface or a migration.
4. If `bounds overview` reports partial coverage, overlaps, cycles, or validation errors, follow `health.validation.next_steps` before trusting that part of the map.
5. On an `E_COVERAGE_GAP`, follow the issue `fix`: add supported files to a manifest's `paths:` (deterministic); for an unsupported language (no adapter yet), author a manifest with a hand-written `exposes:` — durable, calibrate/validate keep it (never stripped or flagged as drift).
6. `bounds validate --quick` after edits; fix drift before broadening context.

### Enforcement (CI is the hard gate, not agent goodwill)
- After manifests exist, wire the gate once: `bounds ci --install --github` (or `--gitlab`) generates the CI config that runs `bounds preflight --ci` on every PR. This — not agent compliance — is the hard enforcement of the contract.
- An **intentional** surface change is not drift to fight: update the manifest, then re-baseline with `bounds calibrate --dump-baseline` and commit `.bounds/drift-baseline.json`. `bounds calibrate --check` then fails only on NEW drift above that baseline.

### Output
- JSON by default — parse it. Add `-H`/`--human` for a readable view of the same data.

### Source of Truth
- GitHub is the single source of truth.
- This repo uses `setuptools-scm` for automatic versioning (no static version string).
- If the local `bounds` CLI is stale, run: `{config.UPGRADE_INSTALL_CMD}`.

### Hard rules
- NEVER read `.bounds/cache.db`, `.bounds/*.json`, `.bounds/manifests/*.yaml`, or `.bounds/root.yaml` directly. The cache is binary; the manifests bypass tree-sitter verification.
- The CLI is the API for architecture. Use source files only for implementation details after Bounds has scoped the subsystem.

### Optional Spec-Driven Development
- If this repo enables `sdd:` in Bounds root config, treat Bounds as the verified architecture layer across specify → clarify → plan → tasks → analyze → implement → verify.
- Bounds does not run the prose workflow and never calls an LLM; it supplies deterministic facts (`overview`, `list`, `describe`, `where`, `impact`) and gates (`validate --quick`, `preflight --ci`, `calibrate --check`).
- Intentional contract changes belong in the spec: update the manifest, then re-baseline with `bounds calibrate --dump-baseline`.
"""

# The token-lean body shared by every per-agent *pointer* file. Kept short on purpose:
# its only job is to redirect the agent to AGENTS.md and the essentials.
_AGENT_POINTER_BODY = """\
This project uses **Bounds** to model its architecture as subsystem boundary manifests.
Read the architecture through the Bounds CLI, never by opening raw `.bounds` files.

- Find the right subsystem → `bounds list`
- A subsystem's surface/tables → `bounds describe <name>` (verified, a few hundred tokens — use before opening source)
- Where a symbol/table lives → `bounds where <symbol>`
- What breaks if you change it → `bounds impact <name>`
- Trust/coverage/next steps → `bounds overview`
- After an edit → `bounds validate --quick`

**Never** read `.bounds/cache.db`, `.bounds/*.json`, or `.bounds/manifests/*.yaml` directly —
the cache is binary and the manifests bypass tree-sitter verification. The CLI is the API for architecture.
See `AGENTS.md` for the full contract.
"""

# Marker delimiters for the managed block (other content may live around it).
_MD_START = "<!-- BOUNDS:START -->"
_MD_END = "<!-- BOUNDS:END -->"
_YAML_START = "# BOUNDS:START"
_YAML_END = "# BOUNDS:END"

# The version+hash stamp, emitted as the first line *inside* the markers. The hash covers the
# inner body only (everything between the markers except the stamp line itself), so it is not
# self-referential and stays stable run-to-run for a given body + bounds version.
_MD_STAMP_RE = re.compile(r"<!-- BOUNDS:GENERATED v=(?P<v>\S+) h=(?P<h>[0-9a-f]{8}) -->")
_YAML_STAMP_RE = re.compile(r"# BOUNDS:GENERATED v=(?P<v>\S+) h=(?P<h>[0-9a-f]{8})")

_MARKDOWN = "markdown"
_YAML = "yaml"

VALID_MODES = {"sync", "detect", "check"}

# Stable, documented ordering of the eight supported agents.
AGENT_KEYS = (
    "claude",
    "codex",
    "opencode",
    "gemini",
    "copilot",
    "cursor",
    "aider",
    "windsurf",
)


class _Agent:
    """Static description of one agent's bounds-config target.

    Attributes:
        key: The agent identifier used in ``only`` / reports.
        path: Config file path, relative to the project root (POSIX components).
        dedicated: True when the file is bounds-only (we own the whole file, but still write
            our content as a marked + stamped block so a human's out-of-marker additions and
            front-matter survive a re-sync). False when the file is *shared* infrastructure
            (AGENTS.md, GEMINI.md, copilot, aider) where unrelated content commonly lives.
        fmt: ``markdown`` or ``yaml`` — selects the marker/comment style.
        canonical: True for the agents whose native file *is* ``AGENTS.md`` (codex, opencode);
            ``AGENTS.md`` is written once as the canonical contract, so these are no-ops in the
            per-agent loop and report against ``AGENTS.md``.
    """

    __slots__ = ("key", "path", "dedicated", "fmt", "canonical")

    def __init__(self, key, path, dedicated, fmt, canonical=False):
        self.key = key
        self.path = path
        self.dedicated = dedicated
        self.fmt = fmt
        self.canonical = canonical


_AGENTS = {
    "claude": _Agent("claude", ".claude/commands/bounds.md", True, _MARKDOWN),
    # codex + opencode read AGENTS.md natively — that IS the canonical contract.
    "codex": _Agent("codex", CANONICAL_NAME, False, _MARKDOWN, canonical=True),
    "opencode": _Agent("opencode", CANONICAL_NAME, False, _MARKDOWN, canonical=True),
    "gemini": _Agent("gemini", "GEMINI.md", False, _MARKDOWN),
    "copilot": _Agent("copilot", ".github/copilot-instructions.md", False, _MARKDOWN),
    "cursor": _Agent("cursor", ".cursor/rules/bounds.mdc", True, _MARKDOWN),
    "aider": _Agent("aider", ".aider.conf.yml", False, _YAML),
    "windsurf": _Agent("windsurf", ".windsurf/rules/bounds.md", True, _MARKDOWN),
}

# Always-loaded project memory files. A marked Bounds pointer is upserted here so the agent learns
# about Bounds from the file it ALWAYS reads — not only from an on-demand command/skill. The write
# is non-destructive (``_upsert_block`` creates the file if absent, else refreshes only the marked
# block, preserving the human's own content). Only agents whose always-loaded file is NOT already
# their pointer/canonical target need an entry: gemini→GEMINI.md, codex/opencode→AGENTS.md and
# copilot→its instructions file are already that file, and cursor/windsurf use always-on rule files,
# so the pointer write already lands where the tool always looks. Claude's pointer is a slash-command
# (``.claude/commands/bounds.md``, invoked on demand), so ``CLAUDE.md`` was never wired — this closes
# that gap. The pointer body is the same one every per-agent pointer uses.
_MEMORY_FILES = {"claude": "CLAUDE.md"}


# ---------------------------------------------------------------------------
# Version + hash stamping (confined to agent-config files; never structural JSON)
# ---------------------------------------------------------------------------
def _version() -> str:
    """Installed bounds version, for stamping generated files.

    Reuses the single resolved value from the package (``bounds.__version__``) so the stamp
    always matches what the rest of the CLI reports, and never raises on this structural-free path.
    """
    try:
        from bounds import __version__
        return __version__
    except Exception:  # pragma: no cover - defensive
        return "unknown"


def _body_hash(body: str) -> str:
    """8-char hex digest of an in-marker body (stamp line excluded by the caller).

    Used only to (a) stamp generated files and (b) detect hand-edits / staleness. It never
    feeds any structural hash — the cache and validation engine compute their own digests over
    source content and are wholly independent of this function.
    """
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:8]


def _stamp_line(fmt: str, body: str) -> str:
    """The version+hash stamp line for ``body`` in the requested marker format."""
    h = _body_hash(body)
    if fmt == _YAML:
        return f"# BOUNDS:GENERATED v={_version()} h={h}"
    return f"<!-- BOUNDS:GENERATED v={_version()} h={h} -->"


def _build_block(fmt: str, body: str) -> str:
    """Wrap ``body`` (the inner content, no markers) in markers + a leading version/hash stamp."""
    start, end = (_YAML_START, _YAML_END) if fmt == _YAML else (_MD_START, _MD_END)
    inner = body.rstrip("\n")
    return f"{start}\n{_stamp_line(fmt, inner)}\n{inner}\n{end}"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def run_agent(project_root: Path, *, mode: str, only: set[str] | None = None) -> dict:
    """Run the cross-agent protocol and return a JSON-serializable payload.

    Args:
        project_root: Repository root. Config files are written relative to it.
        mode: One of ``"sync"``, ``"detect"``, ``"check"``.
        only: Optional set of agent keys (from :data:`AGENT_KEYS`) to restrict the operation
            to. ``None`` means all eight agents. ``AGENTS.md`` (the canonical contract) is
            always written on ``sync`` regardless of selection, since every pointer references it.

    Returns:
        A dict whose shape depends on ``mode``. All path lists are sorted and POSIX-relative.

    Raises:
        BoundsError: ``E_USAGE`` for an unknown ``mode`` or an unknown agent key in ``only``.
    """
    root = Path(project_root)
    if mode not in VALID_MODES:
        raise errors.BoundsError(
            errors.E_USAGE,
            f"unknown agent mode {mode!r}",
            fix=f"use one of: {', '.join(sorted(VALID_MODES))}",
        )
    selected = _resolve_selection(only)

    if mode == "detect":
        return _detect(root)
    if mode == "check":
        return _check(root, selected)
    return _sync(root, selected)


# ---------------------------------------------------------------------------
# Selection helpers
# ---------------------------------------------------------------------------
def _resolve_selection(only: set[str] | None) -> list[str]:
    """Validate ``only`` and return the agent keys to operate on, in stable order.

    Raises ``BoundsError(E_USAGE)`` for any unknown key so a typo fails loudly rather than
    silently writing nothing.
    """
    if only is None:
        return list(AGENT_KEYS)
    unknown = sorted(only - set(AGENT_KEYS))
    if unknown:
        raise errors.BoundsError(
            errors.E_USAGE,
            f"unknown agent key(s): {', '.join(unknown)}",
            fix=f"valid keys: {', '.join(AGENT_KEYS)}",
        )
    return [k for k in AGENT_KEYS if k in only]


# ---------------------------------------------------------------------------
# Expected-body resolution (one home: both sync and check ask "what should this file hold?")
# ---------------------------------------------------------------------------
def _expected_body(agent: "_Agent", sdd_cfg: dict | None = None) -> str:
    """The inner in-marker body (no markers, no stamp) this agent's file should currently hold.

    Single source for both the writer (``_sync``) and the verifier (``_check``) so the two can
    never disagree about what "up to date" means.
    """
    sdd_cfg = sdd_cfg or _sdd_config(None)
    if agent.canonical or agent.path == CANONICAL_NAME:
        return _append_sdd_body(CANONICAL_BODY.rstrip("\n"), "canonical", sdd_cfg)
    if agent.dedicated:
        return _append_sdd_body(_dedicated_body(agent).rstrip("\n"), agent.key, sdd_cfg)
    return _append_sdd_body(_pointer_block_body(agent.fmt).rstrip("\n"), agent.key, sdd_cfg)


def _sdd_config(root: Path | None) -> dict:
    """Return resolved SDD config for generated agent artifacts, fail-soft when absent/broken."""
    raw = {}
    if root is not None:
        try:
            found = manifest_loader.find_root(root)
            if found is not None:
                rootm = manifest_loader.load_root(found)
                if isinstance(rootm.sdd, dict):
                    raw = rootm.sdd
        except Exception:  # noqa: BLE001 - agent sync must still work with a broken root manifest
            raw = {}
    enabled = bool(raw.get("enabled", False))
    agent = str(raw.get("agent") or "generic")
    if agent not in config.SDD_AGENTS:
        agent = "generic"
    requested = raw.get("phases")
    if requested is None:
        requested = config.SDD_PHASES
    phases = [p for p in config.SDD_PHASES if p in set(requested)]
    return {"enabled": enabled, "agent": agent, "phases": phases}


def _append_sdd_body(body: str, agent_key: str, sdd_cfg: dict) -> str:
    """Append the active SDD contract to generated agent text only when opted in."""
    if not sdd_cfg.get("enabled"):
        return body
    return body.rstrip("\n") + "\n\n" + _sdd_body(agent_key, sdd_cfg).rstrip("\n")


def _sdd_body(agent_key: str, sdd_cfg: dict) -> str:
    """Agent-facing SDD phase map expressed as Bounds commands, not a new workflow engine."""
    phase_uses = {
        "specify": ("`bounds overview` / `bounds list`", "ground the spec in the real subsystem map, coverage, and boundaries"),
        "clarify": ("`bounds describe <name>` / `bounds where <symbol>`", "answer what the current verified contract of X is"),
        "plan": ("`bounds impact <name>`", "include blast radius and declared boundaries in the implementation plan"),
        "tasks": ("`bounds impact <name>`", "scope and order tasks by subsystem dependency edges"),
        "analyze": ("`bounds validate` / `bounds preflight`", "cross-check plan/tasks against architecture before coding"),
        "implement": ("`bounds validate --quick`", "catch drift after each edit; manifest updates are part of intentional spec changes"),
        "verify": ("`bounds preflight --ci`", "final deterministic architecture gate"),
    }
    lines = [
        "## Bounds in Spec-Driven Development",
        "",
        f"SDD is enabled for `{sdd_cfg.get('agent', 'generic')}`; this `{agent_key}` artifact wires Bounds into the project's customized SDD loop.",
        "Bounds stays zero-LLM: it provides verified architecture facts and gates while the agent handles prose spec work.",
        "",
        "### Phase contract",
    ]
    for phase in config.SDD_PHASES:
        if phase not in set(sdd_cfg.get("phases", config.SDD_PHASES)):
            continue
        command, use = phase_uses[phase]
        lines.append(f"- **{phase}** → {command} — {use}.")
    lines.extend(
        [
            "",
            "### Freshness contract",
            "- If the spec intentionally changes public surface, update the manifest in the same spec/plan change.",
            "- Run `bounds calibrate --dump-baseline` only after the manifest reflects the intended contract.",
            "- `bounds validate --quick` in the edit loop catches accidental drift; `bounds preflight --ci` is the final gate.",
            "- For unsupported-language subsystems, keep hand-authored exposes in the manifest; calibrate routes unverifiable entries to review instead of deleting them.",
        ]
    )
    return "\n".join(lines)


def _front_matter(agent: "_Agent") -> str:
    """Tool-activating front-matter that must sit at the very top of a dedicated file.

    Lives *outside* the managed markers so the tool parses it at line 1 and so a human can
    tweak it without tripping hand-edit detection:
      * Claude — ``description`` surfaces the file as a usable ``/bounds`` slash command.
      * Cursor — ``alwaysApply: true`` makes a ``.mdc`` an always-on rule (no front-matter =
        a dormant "Manual" rule).
      * Windsurf — ``trigger: always_on`` applies the rule universally.
    Agents without dedicated front-matter return ``""``.
    """
    desc = "Read this project's architecture via the Bounds CLI, not raw .bounds files"
    front = {
        "claude": f"---\ndescription: {desc}\n---\n",
        "cursor": f"---\ndescription: {desc}\nalwaysApply: true\n---\n",
        "windsurf": f"---\ntrigger: always_on\ndescription: {desc}\n---\n",
    }
    return front.get(agent.key, "")


def _dedicated_body(agent: "_Agent") -> str:
    """Inner body for a dedicated (bounds-only) file's managed block.

    Claude's file is a real slash command, so it forwards ``$ARGUMENTS`` to the CLI: running
    ``/bounds describe auth`` actually executes ``bounds describe auth`` (and a bare ``/bounds``
    falls back to ``bounds overview -H``). The CLI keeps space-separated subcommands — we never
    rename a command or hyphenate it. Cursor/Windsurf get the short shared pointer body (they
    are passive always-on rules, not invokable commands).
    """
    if agent.key == "claude":
        return _CLAUDE_COMMAND_BODY
    return "# Bounds\n\n" + _AGENT_POINTER_BODY


# The Claude slash-command body. A thin pointer that *forwards* arguments to the CLI so the
# command is actually runnable, with a short usage list. `$ARGUMENTS` is Claude Code's verbatim
# substitution of whatever follows `/bounds`; empty args default to the overview.
_CLAUDE_COMMAND_BODY = """\
# /bounds

Run the **Bounds** CLI to read this project's architecture (subsystem boundaries, public
surfaces, drift) — never read raw `.bounds/` files. Output is JSON by default;
add `-H` for human-readable.

Run:

```
bounds $ARGUMENTS
```

If no arguments were given, show the map instead:

```
bounds overview -H
```

Usage — `/bounds <subcommand> [args]` forwards verbatim to `bounds <subcommand> [args]`:
- `/bounds list` — all subsystems (roles + dependency counts)
- `/bounds describe <name>` — one subsystem's verified public surface/table catalog (a few hundred tokens for a small subsystem)
- `/bounds describe --namespace <ns>` — every subsystem in a namespace
- `/bounds where <symbol>` — locate a symbol/table without grepping
- `/bounds validate --quick` — catch drift after a change
- `/bounds impact <name>` — transitive blast radius before a risky code or schema change
- `/bounds overview -H` — project health at a glance

Never read `.bounds/cache.db`, `.bounds/*.json`, or `.bounds/manifests/*.yaml` directly — the
cache is binary and the manifests bypass tree-sitter verification. The CLI is the API for architecture. See
`AGENTS.md` for the full contract.
"""


def _pointer_block_body(fmt: str) -> str:
    """The inner body (no markers) for a shared *pointer* file in the requested format."""
    if fmt == _YAML:
        return "\n".join(
            [
                "# Bounds models this codebase as subsystem boundary manifests.",
                "# Read architecture via the CLI, never raw .bounds files:",
                "#   bounds list / bounds describe <name> / bounds validate --quick",
                "# Never read .bounds/cache.db, .bounds/*.json, or .bounds/manifests/*.yaml.",
                "# The CLI is the API for architecture. See AGENTS.md for the full contract.",
                "read: [AGENTS.md]",
            ]
        )
    return "## Bounds\n\n" + _AGENT_POINTER_BODY.rstrip("\n")


# ===========================================================================
# Targeted, invokable command/skill artifacts (native to each agent)
# ---------------------------------------------------------------------------
# Beyond the always-on pointer file, each agent that supports a *committable, invokable* command
# or auto-triggering skill gets one — generated in that tool's native location + format, so the
# agent can act on Bounds directly (a real `/bounds`, an auto-firing skill) instead of only being
# told to. Each artifact is bounds-owned (dedicated) and marker-managed, so re-sync is idempotent
# and a human's hand-edit is never clobbered. Agents with no committable command mechanism (aider)
# get none — we never fake a file a tool won't load.
# ===========================================================================

# The auto-trigger description for skill files (Claude/Codex). It is the matcher the model reads
# to decide *when* to invoke — so it is written as concrete trigger conditions, not a tagline.
_SKILL_TRIGGER = (
    "Read this codebase's architecture with the Bounds CLI before grepping or opening implementation files. "
    "Use when exploring an unfamiliar area, when you need a subsystem's public surface or database "
    "tables, before changing a shared or core subsystem or a migration (check blast radius first), "
    "when asked what depends on X or what breaks if X changes, or to verify drift after an edit. "
    "Never read .bounds/ files directly."
)

# Markdown body shared by the skill files — the task -> command decision table.
_SKILL_BODY = """\
# Bounds — architecture navigation

Read this project's architecture through the Bounds CLI; never open `.bounds/` files or grep for
structure first. Output is JSON by default; add `-H` for human-readable.

## Which command for which task
- Find the right subsystem / get the map → `bounds list`
- A subsystem's verified public surface or DB tables → `bounds describe <name>`
- Where a symbol or table is defined → `bounds where <symbol>`
- Blast radius before changing a subsystem or migration → `bounds impact <name>`
- Catch drift after an edit → `bounds validate --quick`

Run `bounds guide` for setup; see `AGENTS.md` for the full contract.
"""

# Gemini custom command (TOML). `#` comments are valid TOML, so the YAML marker style wraps it.
# `{{args}}` is Gemini's argument placeholder.
_GEMINI_TOML_BODY = '''\
description = "Read this project's architecture via the Bounds CLI (subsystems, surfaces, drift)."
prompt = """
Use the Bounds CLI to answer the user's architecture question; never read .bounds/ files.
Run the right command and summarize its JSON:
- bounds list — the subsystem map
- bounds describe <name> — a subsystem's verified surface/tables
- bounds impact <name> — blast radius before a change
- bounds validate --quick — drift after an edit

User request: {{args}}
"""'''

# OpenCode custom command (Markdown). `$ARGUMENTS` forwards the user's input.
_OPENCODE_CMD_BODY = """\
Read this project's architecture via the Bounds CLI — never read `.bounds/` files.

Run:

```
bounds $ARGUMENTS
```

If no arguments were given, run `bounds overview -H`. Common commands: `list`,
`describe <name>`, `impact <name>`, `validate --quick`, `where <symbol>`.
"""

# GitHub Copilot prompt file (Markdown). `${input:...}` is Copilot's input-variable syntax.
_COPILOT_PROMPT_BODY = """\
Read this project's architecture via the Bounds CLI — never open `.bounds/` files.

Run the right command and summarize its JSON:
- `bounds list` — the subsystem map
- `bounds describe <name>` — a subsystem's verified surface/tables
- `bounds impact <name>` — blast radius before a change
- `bounds validate --quick` — drift after an edit

Task: ${input:task:What do you want to know about the architecture?}
"""

# Cursor command (Markdown prompt template; Cursor commands take no bound arguments).
_CURSOR_CMD_BODY = """\
# Bounds

Use the Bounds CLI to scope this project's architecture before grepping or opening implementation files:

- `bounds list` — the subsystem map
- `bounds describe <name>` — a subsystem's verified surface/tables
- `bounds impact <name>` — blast radius before a change
- `bounds validate --quick` — drift after an edit

Never read `.bounds/` files directly. See `AGENTS.md` for the full contract.
"""

# Windsurf workflow (Markdown; workflows take no bound arguments, so steps prompt for the name).
_WINDSURF_WORKFLOW_BODY = """\
# Bounds

Read this project's architecture via the Bounds CLI — never read `.bounds/` files.

1. Unsure of the layout? Run `bounds list`.
2. Need a subsystem's surface/tables? Run `bounds describe <name>`.
3. About to change a shared subsystem or a migration? Run `bounds impact <name>` first.
4. After an edit, run `bounds validate --quick` and fix drift.
"""


class _Artifact:
    """One bounds-owned command/skill file in an agent's native location.

    ``front`` is leading content that must sit at line 1 (YAML front-matter for a skill/prompt),
    written outside the managed markers like a dedicated pointer file's front-matter. ``fmt``
    selects the marker style (``_YAML`` ``#`` markers are valid in TOML too).
    """

    __slots__ = ("path", "fmt", "body", "front")

    def __init__(self, path: str, fmt: str, body: str, front: str = ""):
        self.path = path
        self.fmt = fmt
        self.body = body
        self.front = front


def _skill_front() -> str:
    """YAML front-matter for a SKILL.md — ``name`` (display) + the auto-trigger ``description``."""
    return f"---\nname: bounds\ndescription: {_SKILL_TRIGGER}\n---\n"


_ARTIFACT_DESC = "Read this project's architecture via the Bounds CLI, not raw .bounds files"

# Per-agent native artifacts. Keys mirror AGENT_KEYS; an agent absent here (aider) gets only its
# always-on pointer, since it has no committable command mechanism to target.
_AGENT_ARTIFACTS: dict[str, tuple[_Artifact, ...]] = {
    # Claude & Codex: auto-triggering skills (the description fires them). Claude keeps its own
    # `.claude/skills/`; Codex loads from the cross-tool open Agent Skills location
    # `.agents/skills/` (the shared spec Codex/Cursor/Gemini/Copilot/VS Code adopted).
    "claude": (_Artifact(".claude/skills/bounds/SKILL.md", _MARKDOWN, _SKILL_BODY, _skill_front()),),
    "codex": (_Artifact(".agents/skills/bounds/SKILL.md", _MARKDOWN, _SKILL_BODY, _skill_front()),),
    # Gemini: TOML custom command -> /bounds.
    "gemini": (_Artifact(".gemini/commands/bounds.toml", _YAML, _GEMINI_TOML_BODY),),
    # OpenCode: Markdown custom command -> /bounds (project commands live in `.opencode/commands/`,
    # plural — see https://opencode.ai/docs/commands/; the singular dir was never discovered).
    "opencode": (
        _Artifact(".opencode/commands/bounds.md", _MARKDOWN, _OPENCODE_CMD_BODY,
                  f"---\ndescription: {_ARTIFACT_DESC}\nagent: build\n---\n"),
    ),
    # Copilot: prompt file -> /bounds.
    "copilot": (
        _Artifact(".github/prompts/bounds.prompt.md", _MARKDOWN, _COPILOT_PROMPT_BODY,
                  f"---\nmode: agent\ndescription: {_ARTIFACT_DESC}\n---\n"),
    ),
    # Cursor: command -> /bounds (the always-on rule is the per-agent pointer file).
    "cursor": (_Artifact(".cursor/commands/bounds.md", _MARKDOWN, _CURSOR_CMD_BODY),),
    # Windsurf: workflow -> /bounds (the always-on rule is the per-agent pointer file).
    "windsurf": (
        _Artifact(".windsurf/workflows/bounds.md", _MARKDOWN, _WINDSURF_WORKFLOW_BODY,
                  f"---\ndescription: {_ARTIFACT_DESC}\n---\n"),
    ),
}

# Bounds-owned artifact paths that were RENAMED after we already shipped them, so repos synced
# by an older bounds carry a stale orphan at the old path. These are regenerable (the *correct*
# paths are written in the `_AGENT_ARTIFACTS` loop of this same sync), so a re-sync self-cleans
# the orphan — the same self-clean pattern as the legacy state.json in `cache.store.save_state`.
# Each here is provably NOT a current artifact path: opencode's singular `command/` was renamed to
# the plural `commands/`, and codex's `.codex/skills/` was renamed to the shared `.agents/skills/`
# spec location — so removing these can never delete a file this sync just wrote.
_LEGACY_ARTIFACTS: tuple[tuple[str, str], ...] = (
    # (legacy path, owning agent) — cleaned only when that agent is in THIS sync, so the
    # replacement (written above in the _AGENT_ARTIFACTS loop) is guaranteed present.
    (".opencode/command/bounds.md", "opencode"),   # -> .opencode/commands/bounds.md (plural)
    (".codex/skills/bounds/SKILL.md", "codex"),     # -> .agents/skills/bounds/SKILL.md (open spec)
)


# ---------------------------------------------------------------------------
# mode = sync
# ---------------------------------------------------------------------------
def _sync(root: Path, selected: list[str]) -> dict:
    """Write the canonical ``AGENTS.md`` and the selected agents' pointer files.

    ``AGENTS.md`` is always (re)written first — it is the source of truth every pointer
    references — then each selected agent that has its *own* file gets a marked, stamped block.
    Codex/OpenCode are satisfied by ``AGENTS.md`` itself, so selecting them is a no-op beyond
    the canonical write.

    Every file is marker-managed: content *outside* the markers (including a dedicated file's
    front-matter and any human additions) is preserved byte-for-byte, and only the block inside
    the markers is refreshed. If a file's in-marker body was hand-edited since we last stamped
    it (its content no longer matches the recorded hash), it is reported ``skipped_custom`` and
    left untouched rather than clobbered.

    Returns sorted, POSIX-relative ``created`` / ``updated`` / ``unchanged`` / ``skipped_custom``
    path lists, a ``skip_reasons`` map (``path -> "authored" | "hand-edited"``) explaining each
    skip, and ``canonical`` (always ``"AGENTS.md"``). ``unchanged`` lets a no-op sync confirm
    "everything already current" instead of looking like nothing happened.
    """
    buckets = _Buckets()
    sdd_cfg = _sdd_config(root)

    # 1. Canonical AGENTS.md — always written, as a marked block so any other AGENTS.md
    #    content the project keeps is preserved.
    canonical_path = root / CANONICAL_NAME
    rel_canonical = CANONICAL_NAME
    outcome = _upsert_block(
        canonical_path,
        _MARKDOWN,
        _expected_body(_AGENTS["codex"], sdd_cfg),
    )
    buckets.record(outcome, rel_canonical)

    # 2. Per-tool files for the selected agents (AGENTS.md already handled above).
    done: set[str] = {CANONICAL_NAME}
    for key in selected:
        agent = _AGENTS[key]
        if agent.canonical or agent.path in done:
            continue  # covered by the canonical AGENTS.md write
        done.add(agent.path)
        outcome = _upsert_block(
            root / Path(agent.path),
            agent.fmt,
            _expected_body(agent, sdd_cfg),
            prefix=_front_matter(agent),
            dedicated=agent.dedicated,
        )
        buckets.record(outcome, Path(agent.path).as_posix())

    # 2b. Always-loaded memory files (e.g. Claude's CLAUDE.md). A marked pointer block so the agent
    #     is told about Bounds from the file it ALWAYS reads, not only an on-demand command/skill.
    #     Non-destructive: created if absent, else the block is added/refreshed while the human's own
    #     content is preserved byte-for-byte. The body is the shared per-agent pointer body.
    for key in selected:
        mem = _MEMORY_FILES.get(key)
        if mem is None or mem in done:
            continue
        done.add(mem)
        outcome = _upsert_block(
            root / Path(mem),
            _MARKDOWN,
            _append_sdd_body(_AGENT_POINTER_BODY.rstrip("\n"), key, sdd_cfg),
        )
        buckets.record(outcome, Path(mem).as_posix())

    # 3. Targeted, invokable command/skill files (native to each agent). Each is bounds-owned
    #    (dedicated), so it is marker-managed + idempotent like the rest. Agents with no
    #    committable command mechanism (aider) have none — never faked.
    for key in selected:
        for art in _AGENT_ARTIFACTS.get(key, ()):
            if art.path in done:
                continue
            done.add(art.path)
            outcome = _upsert_block(
                root / Path(art.path), art.fmt,
                _append_sdd_body(art.body.rstrip("\n"), key, sdd_cfg),
                prefix=art.front, dedicated=True,
            )
            buckets.record(outcome, Path(art.path).as_posix())

    # 4. Self-clean renamed orphans — but ONLY for agents in THIS sync. The step-3 loop above
    #    already wrote the current path for each selected agent, so removing that agent's stale
    #    file at its prior (renamed) path is safe: the replacement is guaranteed present. Gating on
    #    `owner in selected` means a selective sync (e.g. --only gemini) never strips another
    #    agent's file without writing its replacement. Only these exact bounds-owned paths are ever
    #    touched, and none collides with a current artifact (see `_LEGACY_ARTIFACTS`). Fail-soft:
    #    cleanup never raises. An emptied parent dir is removed too, but only if empty — we never
    #    recursively delete a dir that still holds other files.
    selected_set = set(selected)
    for rel, owner in _LEGACY_ARTIFACTS:
        if owner not in selected_set:
            continue
        legacy = root / Path(rel)
        if legacy.is_file():
            try:
                legacy.unlink()
            except OSError:
                pass
            try:
                parent = legacy.parent
                if not any(parent.iterdir()):
                    parent.rmdir()
            except OSError:
                pass

    return {
        "created": sorted(buckets.created),
        "updated": sorted(buckets.updated),
        "unchanged": sorted(buckets.unchanged),
        "skipped_custom": sorted(buckets.skipped),
        "skip_reasons": {k: buckets.reasons[k] for k in sorted(buckets.reasons)},
        "canonical": rel_canonical,
    }


class _Buckets:
    """Accumulates per-file ``_upsert_block`` outcomes into the sync report's sorted lists.

    A skip carries *why* (``"authored"`` = a file the human wrote that already mentions bounds;
    ``"hand-edited"`` = our managed block whose body a human changed) so the human renderer can
    explain it honestly and point at the fix, rather than the old flat "hand-edited" wording that
    mislabeled files which were never bounds-managed in the first place.
    """

    __slots__ = ("created", "updated", "unchanged", "skipped", "reasons")

    def __init__(self) -> None:
        self.created: set[str] = set()
        self.updated: set[str] = set()
        self.unchanged: set[str] = set()
        self.skipped: set[str] = set()
        self.reasons: dict[str, str] = {}

    def record(self, outcome: str, rel: str) -> None:
        if outcome == "created":
            self.created.add(rel)
        elif outcome == "updated":
            self.updated.add(rel)
        elif outcome == "unchanged":
            self.unchanged.add(rel)
        elif outcome == "skipped_authored":
            self.skipped.add(rel)
            self.reasons[rel] = "authored"
        elif outcome == "skipped_hand_edited":
            self.skipped.add(rel)
            self.reasons[rel] = "hand-edited"


def _upsert_block(
    target: Path, fmt: str, body: str, prefix: str = "", dedicated: bool = False
) -> str:
    """Insert or refresh our marked+stamped block in ``target``, preserving other content.

    ``body`` is the inner content (no markers); this wraps it via :func:`_build_block`.
    ``prefix`` is the tool-activating front-matter a dedicated file must lead with. ``dedicated``
    marks a file bounds owns wholly (Claude/Cursor/Windsurf): such a file is always brought up to
    date — a legacy bounds file with no markers is *migrated* to a stamped block rather than
    skipped, and front-matter a human deleted is restored so the tool can't silently de-activate.

    Returns:
        ``created``        — file did not exist; created with ``prefix`` + our block.
        ``updated``        — our marked block was inserted/refreshed, or a dedicated file was
                             migrated / had its front-matter restored.
        ``unchanged``      — file already held our block with an identical body and (for a
                             dedicated file) intact front-matter. A differing version stamp
                             alone does not count as a change.
        ``skipped_hand_edited`` — a *shared* file whose in-marker body a human edited since we
                             stamped it. Left untouched (never clobber a human's edit).
        ``skipped_authored`` — a *shared* file with no markers that already mentions bounds, so a
                             human wrote it. Left untouched. Dedicated files are never skipped —
                             we own them.
    """
    start, end = (_YAML_START, _YAML_END) if fmt == _YAML else (_MD_START, _MD_END)
    block = _build_block(fmt, body)

    if not target.exists():
        _write_text(target, (prefix + "\n" if prefix else "") + block + "\n")
        return "created"

    existing = _read_text(target)

    if start in existing and end in existing:
        current_inner = _extract_inner(existing, start, end)
        if current_inner is not None and _is_hand_edited(current_inner, fmt):
            return "skipped_hand_edited"  # human edited inside the markers — never clobber.

        # Refresh the block, and for a dedicated file restore front-matter a human may have
        # removed (which would otherwise silently de-activate the tool).
        new = _replace_block(existing, start, end, block)
        if dedicated:
            new = _ensure_front_matter(new, prefix)

        # A differing version stamp alone is not a real change: the dev version moves every
        # commit, so decide on the body — and, for a dedicated file that *expects* front-matter
        # (non-empty prefix), its presence. A dedicated file with no front-matter (e.g. a TOML
        # command, a Cursor command) must still read as unchanged when its body matches.
        current_body = _split_stamp(current_inner, fmt)[2] if current_inner is not None else None
        front_ok = not dedicated or not prefix or _has_front_matter(existing)
        if current_body == body and front_ok:
            return "unchanged"
        _write_text(target, new)
        return "updated"

    # No markers.
    if dedicated:
        # We own a dedicated file wholly: migrate legacy bounds content (written before stamping
        # existed) into a stamped block, keeping any front-matter a human may have tweaked.
        front = _leading_front_matter(existing) or prefix
        _write_text(target, (front + "\n" if front else "") + block + "\n")
        return "updated"

    # Shared file: if it already talks about bounds, a human wrote it — don't clobber.
    if _looks_bounds_authored(existing):
        return "skipped_authored"

    # Unrelated content with no markers: append our block, preserving theirs.
    sep = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    _write_text(target, existing + sep + block + "\n")
    return "updated"


def _has_front_matter(text: str) -> bool:
    """True when ``text`` opens (at line 1) with a ``---``-fenced front-matter block.

    The fence must lead the file for the tool to parse it, so a leading blank line counts as
    missing — and a re-sync will restore it.
    """
    return text.startswith("---")


def _leading_front_matter(text: str) -> str:
    """Return the leading ``---``-fenced front-matter block (trailing newline included), or ``""``."""
    if not text.startswith("---"):
        return ""
    lines = text.split("\n")
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            return "\n".join(lines[: idx + 1]) + "\n"
    return ""


def _ensure_front_matter(text: str, prefix: str) -> str:
    """Restore a dedicated file's leading front-matter when a human removed it.

    Without it the tool silently de-activates (Claude drops the ``/bounds`` command, Cursor and
    Windsurf stop auto-applying their rule). An existing front-matter is left untouched so a
    human's edits to the description survive.
    """
    if not prefix or _has_front_matter(text):
        return text
    return prefix + "\n" + text


def _extract_inner(text: str, start: str, end: str) -> str | None:
    """Return the content between the first ``start`` and ``end`` markers (exclusive), or None.

    The returned text is the *raw* in-marker block, stamp line included; callers strip the
    stamp themselves when they need the body alone.
    """
    i = text.find(start)
    if i == -1:
        return None
    j = text.find(end, i + len(start))
    if j == -1:
        return None
    return text[i + len(start):j].strip("\n")


def _split_stamp(inner: str, fmt: str) -> tuple[str | None, str | None, str]:
    """Split a raw in-marker block into ``(version, hash, body)``.

    The stamp is the first line when present; ``version``/``hash`` are None for a legacy
    (un-stamped) block, with the whole text returned as the body.
    """
    pattern = _YAML_STAMP_RE if fmt == _YAML else _MD_STAMP_RE
    lines = inner.split("\n")
    if lines:
        m = pattern.fullmatch(lines[0].strip())
        if m:
            return m.group("v"), m.group("h"), "\n".join(lines[1:]).strip("\n")
    return None, None, inner


def _is_hand_edited(inner: str, fmt: str) -> bool:
    """True when an existing in-marker block was edited by a human since we stamped it.

    A block we wrote carries a stamp whose hash matches its body. If the recorded hash and the
    body's actual hash disagree, a human touched the content — refuse to clobber it. A legacy
    block with no stamp at all is treated as ours (we wrote it before stamping existed), so it
    is safe to refresh.
    """
    _v, recorded, body = _split_stamp(inner, fmt)
    if recorded is None:
        return False  # legacy un-stamped block we authored — safe to refresh.
    return _body_hash(body) != recorded


def _replace_block(text: str, start: str, end: str, block: str) -> str:
    """Replace the first ``start``…``end`` marked region (inclusive) with ``block``.

    Operates on the raw text so surrounding content — before the start marker and after the
    end marker — is preserved byte-for-byte.
    """
    i = text.index(start)
    j = text.index(end, i) + len(end)
    return text[:i] + block + text[j:]


_BOUNDS_COMMAND_RE = re.compile(
    r"\bbounds\s+"
    r"(list|describe|validate|preflight|overview|init|impact|discover|calibrate|agent|ci|cache)\b"
)
_BOUNDS_HEADING_RE = re.compile(r"(?m)^\s*#.*\bbounds\b")


def _looks_bounds_authored(text: str) -> bool:
    """Heuristic: does an unmarked shared file already contain hand-written bounds content?

    Used only to decide ``skipped_custom``. We look for unambiguous signals that a human wrote
    bounds guidance, so we err toward *not* clobbering:
      * a real CLI invocation — the word ``bounds`` immediately followed by a known subcommand;
      * the inline-code form ```` `bounds` ````;
      * a markdown heading line that names Bounds.

    Critically, plain English prose such as "out of bounds" or "bounds checking" must NOT
    match — those are safe to append our block to. Returns False for any such unrelated content.
    """
    lowered = text.lower()
    return (
        bool(_BOUNDS_COMMAND_RE.search(lowered))
        or "`bounds`" in lowered
        or bool(_BOUNDS_HEADING_RE.search(lowered))
    )


# ---------------------------------------------------------------------------
# mode = detect
# ---------------------------------------------------------------------------
def _detect(root: Path) -> dict:
    """Heuristically report which agents' tool footprints are present in ``root``.

    Heuristic (presence of the agent's native footprint, independent of whether bounds has
    been synced yet):
      * claude   — ``.claude/`` directory exists.
      * codex    — ``AGENTS.md`` exists (Codex's instruction file).
      * opencode — ``AGENTS.md`` exists (OpenCode shares the same file).
      * gemini   — ``GEMINI.md`` exists.
      * copilot  — ``.github/copilot-instructions.md`` exists (its actual instruction file — a
        bare ``.github/`` directory is universal and not a Copilot signal).
      * cursor   — ``.cursor/`` directory exists.
      * aider    — ``.aider.conf.yml`` exists.
      * windsurf — ``.windsurf/`` directory exists.

    Returns ``{"detected": [sorted agent keys]}``.
    """
    detected = [k for k in AGENT_KEYS if _footprint_present(root, k)]
    return {"detected": sorted(detected)}


def _footprint_present(root: Path, key: str) -> bool:
    """True when ``key``'s native tool footprint exists under ``root`` (see :func:`_detect`)."""
    checks = {
        "claude": (root / ".claude").is_dir,
        "codex": (root / CANONICAL_NAME).is_file,
        "opencode": (root / CANONICAL_NAME).is_file,
        "gemini": (root / "GEMINI.md").is_file,
        "copilot": (root / ".github" / "copilot-instructions.md").is_file,
        "cursor": (root / ".cursor").is_dir,
        "aider": (root / ".aider.conf.yml").is_file,
        "windsurf": (root / ".windsurf").is_dir,
    }
    return checks[key]()


# ---------------------------------------------------------------------------
# mode = check
# ---------------------------------------------------------------------------
def _check(root: Path, selected: list[str]) -> dict:
    """Report, for each detected-and-selected agent, whether its bounds config is up to date.

    We intersect with detection so a check reports only on agents actually in use — selecting
    all eight on a Claude-only repo won't flag cursor/gemini/etc. We classify each target as:

      * ``missing``    — the config file doesn't exist, or exists but carries no bounds block
                         (no markers / never synced).
      * ``stale``      — a bounds block is present but its content no longer matches what the
                         installed CLI would generate (the contract moved on, the body was
                         hand-edited, or — for a dedicated file — its front-matter was removed).
                         Refresh with ``bounds agent --sync``.
      * ``configured`` — a bounds block is present and its stamped hash matches the current
                         expected body exactly.

    Returns ``{"ok": bool, "missing": [...], "stale": [...], "configured": [...], "fix": "..."}``
    with sorted key lists; ``ok`` is True iff nothing is missing *and* nothing is stale. The
    ``fix`` field is only present when there is something to fix.
    """
    detected = set(_detect(root)["detected"])
    targets = [k for k in selected if k in detected]
    sdd_cfg = _sdd_config(root)

    configured: list[str] = []
    missing: list[str] = []
    stale: list[str] = []
    for key in targets:
        status = _config_status(root, _AGENTS[key], sdd_cfg)
        if status == "missing":
            missing.append(key)
        elif status == "stale":
            stale.append(key)
        else:
            configured.append(key)

    result: dict = {
        "ok": not missing and not stale,
        "missing": sorted(missing),
        "stale": sorted(stale),
        "configured": sorted(configured),
    }
    if missing or stale:
        result["fix"] = "bounds agent --sync"
    return result


def _config_status(root: Path, agent: "_Agent", sdd_cfg: dict | None = None) -> str:
    """Classify ``agent`` as ``missing`` / ``stale`` / ``configured`` across ALL its files.

    The primary signal is the pointer/canonical file (``missing`` ⇒ never synced; ``stale`` ⇒
    synced-but-outdated). On top of that, any native command/skill artifact that is *present but
    corrupted/outdated* (a hand-edit, an old stamp) downgrades the agent to ``stale`` — that is the
    real risk the gate must catch, since the tool would load a broken file. A merely *absent*
    artifact does not: it is an un-generated enhancement that an idempotent re-sync adds
    non-destructively, and several agents (codex/opencode) are fully wired by ``AGENTS.md`` alone,
    so requiring their optional artifact would falsely flag them after a single-agent sync.
    """
    sdd_cfg = sdd_cfg or _sdd_config(root)
    pointer = _target_status(root, agent.path, agent.fmt, _expected_body(agent, sdd_cfg),
                             agent.dedicated, _front_matter(agent))
    if pointer != "configured":
        return pointer  # missing (never synced) or stale (outdated) — primary signal wins
    for art in _AGENT_ARTIFACTS.get(agent.key, ()):
        if (root / Path(art.path)).exists():
            body = _append_sdd_body(art.body.rstrip("\n"), agent.key, sdd_cfg)
            if _target_status(root, art.path, art.fmt, body, True, art.front) != "configured":
                return "stale"  # a present artifact is broken/outdated — re-sync to refresh
    # An always-loaded memory file (CLAUDE.md) that exists but lacks/holds an outdated bounds block
    # downgrades to stale so the gate tells you to re-sync. A merely-absent one does not (an
    # idempotent --sync creates it non-destructively), mirroring the optional-artifact rule above.
    mem = _MEMORY_FILES.get(agent.key)
    if mem is not None and (root / Path(mem)).exists():
        mem_body = _append_sdd_body(_AGENT_POINTER_BODY.rstrip("\n"), agent.key, sdd_cfg)
        if _target_status(root, mem, _MARKDOWN, mem_body, False, "") != "configured":
            return "stale"
    return "configured"


def _target_status(root: Path, rel: str, fmt: str, expected_body: str,
                   dedicated: bool, front: str) -> str:
    """Classify one managed file as ``missing`` / ``stale`` / ``configured``.

    "Up to date" means the file has our markers AND the in-marker block carries a stamp whose
    hash matches what the installed CLI would generate now. A present-but-un-stamped block, an
    older-hash stamp, a hand-edited body, or (for a dedicated file that expects it) removed
    front-matter all read as ``stale``. The version string is deliberately not part of staleness —
    it moves every commit, so the body hash is the contract signal.
    """
    target = root / Path(rel)
    if not target.exists():
        return "missing"
    start = _YAML_START if fmt == _YAML else _MD_START
    end = _YAML_END if fmt == _YAML else _MD_END
    text = _read_text(target)
    if start not in text or end not in text:
        return "missing"  # file exists but was never synced (no bounds block)
    inner = _extract_inner(text, start, end)
    if inner is None:
        return "missing"
    _version_stamp, recorded, body = _split_stamp(inner, fmt)
    if recorded is None or recorded != _body_hash(expected_body):
        return "stale"
    if _body_hash(body) != recorded:
        return "stale"
    if dedicated and front and not _has_front_matter(text):
        return "stale"
    return "configured"


# ---------------------------------------------------------------------------
# Filesystem helpers (centralized so encoding/newlines stay consistent)
# ---------------------------------------------------------------------------
def _read_text(path: Path) -> str:
    """Read a file as UTF-8 text (no surprises across platforms)."""
    return path.read_text(encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    """Write UTF-8 text, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
