"""Cross-agent protocol: teach coding agents to read architecture via the CLI.

The problem this solves: AI coding agents (Claude Code, Cursor, Copilot, Gemini, …) each
have their own out-of-band convention for project instructions, and when left to their own
devices they read the raw `.bounds/` files — the binary cache and the unverified YAML
manifests — which both defeats tree-sitter verification *and* burns context on data the CLI
already compresses.

This module writes a single canonical contract in ``AGENTS.md`` — the cross-ecosystem
standard file that agents already read — plus a small per-agent *pointer* file in each
agent's native config location, all conveying the same essentials: use ``bounds list`` /
``bounds describe`` / ``bounds validate --quick``, never read the raw files, and treat the CLI
as the API. ``AGENTS.md`` is the source of truth; every per-tool pointer references it, so
there is exactly one place the contract lives.

Design constraints (enforced repo-wide):
  * Pure stdlib, no new dependencies.
  * These are *generated artifacts*, not structural JSON. Each managed block is wrapped in
    ``<!-- BOUNDS:START -->`` / ``<!-- BOUNDS:END -->`` markers and stamped with the bounds
    version + an 8-char content hash. That stamp is the ONLY non-deterministic element and it
    is confined to these agent-config files — it never reaches any ``describe`` / ``validate``
    / ``list`` JSON, nor any cache/validation hash. Everything *around* a managed block (and
    the body apart from the stamp) is deterministic, so a re-sync of unedited files is a no-op.
  * Fail soft: the only fatal condition is genuine misuse (bad ``mode`` / bad agent key),
    which raises ``BoundsError(E_USAGE)``. A pre-existing hand-written config — whether it has
    no markers but mentions bounds, or has markers whose body a human edited — is never
    clobbered; it is reported (``skipped_custom``) and left untouched.

The three modes:
  * ``sync``   — write ``AGENTS.md`` and the selected agents' pointer files; return what changed.
  * ``detect`` — heuristically report which agents' tool footprints are present.
  * ``check``  — for detected agents, report which have a stale/missing bounds config.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

from . import errors

# ---------------------------------------------------------------------------
# Canonical contract content (committed in AGENTS.md; the single source of truth)
# ---------------------------------------------------------------------------
CANONICAL_NAME = "AGENTS.md"

# AGENTS.md is GENERATED by `bounds agent --sync` from CANONICAL_BODY below — the committed file
# is just its rendered output. Make any contract change (including the Source of Truth / staleness
# block) HERE and regenerate with `bounds agent --sync`; edits made directly to AGENTS.md are
# overwritten on the next sync.
#
# The full contract. Lives inside AGENTS.md's marked block so it coexists with any other
# AGENTS.md content a project already keeps. The leading warning line is intentional: it tells
# a human reader (and any agent) that the block is machine-managed.
CANONICAL_BODY = """\
> Managed by `bounds agent --sync` — edits inside this block are overwritten; edit the generator (`src/bounds/agentsync.py`) instead.

## Bounds — architecture contract for agents

Bounds models this codebase as subsystem boundary manifests. Query them through the CLI — never read the raw files.

### Commands
- `bounds list` — all subsystems (the map; roles + dependency counts)
- `bounds describe <name>` — one subsystem's public surface (a few hundred tokens for a small subsystem, tree-sitter-verified)
- `bounds describe --namespace <ns>` — every subsystem in a namespace
- `bounds validate --quick` — catch drift after a change
- `bounds impact <name>` — transitive blast radius before a risky change

### Source of Truth
- GitHub is the single source of truth.
- This repo uses `setuptools-scm` for automatic versioning (no static version string).
- If the local `bounds` CLI is stale, run: `pipx install --force git+https://github.com/Farzin312/bounds.git`.

### Hard rules
- NEVER read `.bounds/cache.db`, `.bounds/*.json`, `.bounds/manifests/*.yaml`, or `.bounds/root.yaml` directly. The cache is binary; the manifests bypass tree-sitter verification.
- The CLI is the API. Always use `bounds` commands to read architecture.
"""

# The token-lean body shared by every per-agent *pointer* file. Kept short on purpose:
# its only job is to redirect the agent to AGENTS.md and the essentials.
_AGENT_POINTER_BODY = """\
This project uses **Bounds** to model its architecture as subsystem boundary manifests.
Read the architecture through the Bounds CLI, never by opening the raw files.

- `bounds list` — map of all subsystems (roles + dependency counts)
- `bounds describe <name>` — one subsystem's verified public surface (a few hundred tokens for a small subsystem)
- `bounds validate --quick` — catch structural drift after a change

**Never** read `.bounds/cache.db`, `.bounds/*.json`, or `.bounds/manifests/*.yaml` directly —
the cache is binary and the manifests bypass tree-sitter verification. The CLI is the API.
See `AGENTS.md` for the full contract.
"""

# Marker delimiters for the managed block (other content may live around it).
_MD_START = "<!-- BOUNDS:START -->"
_MD_END = "<!-- BOUNDS:END -->"
_YAML_START = "# BOUNDS:START"
_YAML_END = "# BOUNDS:END"

# The version+hash stamp, emitted as the first line *inside* the markers. The hash covers the
# inner body only (everything between the markers except the stamp line itself), so it is not
# self-referential and stays stable run-to-run for a given body + bounds version.
_MD_STAMP_RE = re.compile(r"<!-- BOUNDS:GENERATED v=(?P<v>\S+) h=(?P<h>[0-9a-f]{8}) -->")
_YAML_STAMP_RE = re.compile(r"# BOUNDS:GENERATED v=(?P<v>\S+) h=(?P<h>[0-9a-f]{8})")

_MARKDOWN = "markdown"
_YAML = "yaml"

VALID_MODES = {"sync", "detect", "check"}

# Stable, documented ordering of the eight supported agents.
AGENT_KEYS = (
    "claude",
    "codex",
    "opencode",
    "gemini",
    "copilot",
    "cursor",
    "aider",
    "windsurf",
)


class _Agent:
    """Static description of one agent's bounds-config target.

    Attributes:
        key: The agent identifier used in ``only`` / reports.
        path: Config file path, relative to the project root (POSIX components).
        dedicated: True when the file is bounds-only (we own the whole file, but still write
            our content as a marked + stamped block so a human's out-of-marker additions and
            front-matter survive a re-sync). False when the file is *shared* infrastructure
            (AGENTS.md, GEMINI.md, copilot, aider) where unrelated content commonly lives.
        fmt: ``markdown`` or ``yaml`` — selects the marker/comment style.
        canonical: True for the agents whose native file *is* ``AGENTS.md`` (codex, opencode);
            ``AGENTS.md`` is written once as the canonical contract, so these are no-ops in the
            per-agent loop and report against ``AGENTS.md``.
    """

    __slots__ = ("key", "path", "dedicated", "fmt", "canonical")

    def __init__(self, key, path, dedicated, fmt, canonical=False):
        self.key = key
        self.path = path
        self.dedicated = dedicated
        self.fmt = fmt
        self.canonical = canonical


_AGENTS = {
    "claude": _Agent("claude", ".claude/commands/bounds.md", True, _MARKDOWN),
    # codex + opencode read AGENTS.md natively — that IS the canonical contract.
    "codex": _Agent("codex", CANONICAL_NAME, False, _MARKDOWN, canonical=True),
    "opencode": _Agent("opencode", CANONICAL_NAME, False, _MARKDOWN, canonical=True),
    "gemini": _Agent("gemini", "GEMINI.md", False, _MARKDOWN),
    "copilot": _Agent("copilot", ".github/copilot-instructions.md", False, _MARKDOWN),
    "cursor": _Agent("cursor", ".cursor/rules/bounds.mdc", True, _MARKDOWN),
    "aider": _Agent("aider", ".aider.conf.yml", False, _YAML),
    "windsurf": _Agent("windsurf", ".windsurf/rules/bounds.md", True, _MARKDOWN),
}


# ---------------------------------------------------------------------------
# Version + hash stamping (confined to agent-config files; never structural JSON)
# ---------------------------------------------------------------------------
def _version() -> str:
    """Installed bounds version, for stamping generated files.

    Reuses the single resolved value from the package (``bounds.__version__``) so the stamp
    always matches what the rest of the CLI reports, and never raises on this structural-free path.
    """
    try:
        from bounds import __version__
        return __version__
    except Exception:  # pragma: no cover - defensive
        return "unknown"


def _body_hash(body: str) -> str:
    """8-char hex digest of an in-marker body (stamp line excluded by the caller).

    Used only to (a) stamp generated files and (b) detect hand-edits / staleness. It never
    feeds any structural hash — the cache and validation engine compute their own digests over
    source content and are wholly independent of this function.
    """
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:8]


def _stamp_line(fmt: str, body: str) -> str:
    """The version+hash stamp line for ``body`` in the requested marker format."""
    h = _body_hash(body)
    if fmt == _YAML:
        return f"# BOUNDS:GENERATED v={_version()} h={h}"
    return f"<!-- BOUNDS:GENERATED v={_version()} h={h} -->"


def _build_block(fmt: str, body: str) -> str:
    """Wrap ``body`` (the inner content, no markers) in markers + a leading version/hash stamp."""
    start, end = (_YAML_START, _YAML_END) if fmt == _YAML else (_MD_START, _MD_END)
    inner = body.rstrip("\n")
    return f"{start}\n{_stamp_line(fmt, inner)}\n{inner}\n{end}"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def run_agent(project_root: Path, *, mode: str, only: set[str] | None = None) -> dict:
    """Run the cross-agent protocol and return a JSON-serializable payload.

    Args:
        project_root: Repository root. Config files are written relative to it.
        mode: One of ``"sync"``, ``"detect"``, ``"check"``.
        only: Optional set of agent keys (from :data:`AGENT_KEYS`) to restrict the operation
            to. ``None`` means all eight agents. ``AGENTS.md`` (the canonical contract) is
            always written on ``sync`` regardless of selection, since every pointer references it.

    Returns:
        A dict whose shape depends on ``mode``. All path lists are sorted and POSIX-relative.

    Raises:
        BoundsError: ``E_USAGE`` for an unknown ``mode`` or an unknown agent key in ``only``.
    """
    root = Path(project_root)
    if mode not in VALID_MODES:
        raise errors.BoundsError(
            errors.E_USAGE,
            f"unknown agent mode {mode!r}",
            fix=f"use one of: {', '.join(sorted(VALID_MODES))}",
        )
    selected = _resolve_selection(only)

    if mode == "detect":
        return _detect(root)
    if mode == "check":
        return _check(root, selected)
    return _sync(root, selected)


# ---------------------------------------------------------------------------
# Selection helpers
# ---------------------------------------------------------------------------
def _resolve_selection(only: set[str] | None) -> list[str]:
    """Validate ``only`` and return the agent keys to operate on, in stable order.

    Raises ``BoundsError(E_USAGE)`` for any unknown key so a typo fails loudly rather than
    silently writing nothing.
    """
    if only is None:
        return list(AGENT_KEYS)
    unknown = sorted(only - set(AGENT_KEYS))
    if unknown:
        raise errors.BoundsError(
            errors.E_USAGE,
            f"unknown agent key(s): {', '.join(unknown)}",
            fix=f"valid keys: {', '.join(AGENT_KEYS)}",
        )
    return [k for k in AGENT_KEYS if k in only]


# ---------------------------------------------------------------------------
# Expected-body resolution (one home: both sync and check ask "what should this file hold?")
# ---------------------------------------------------------------------------
def _expected_body(agent: "_Agent") -> str:
    """The inner in-marker body (no markers, no stamp) this agent's file should currently hold.

    Single source for both the writer (``_sync``) and the verifier (``_check``) so the two can
    never disagree about what "up to date" means.
    """
    if agent.canonical or agent.path == CANONICAL_NAME:
        return CANONICAL_BODY.rstrip("\n")
    if agent.dedicated:
        return _dedicated_body(agent).rstrip("\n")
    return _pointer_block_body(agent.fmt).rstrip("\n")


def _front_matter(agent: "_Agent") -> str:
    """Tool-activating front-matter that must sit at the very top of a dedicated file.

    Lives *outside* the managed markers so the tool parses it at line 1 and so a human can
    tweak it without tripping hand-edit detection:
      * Claude — ``description`` surfaces the file as a usable ``/bounds`` slash command.
      * Cursor — ``alwaysApply: true`` makes a ``.mdc`` an always-on rule (no front-matter =
        a dormant "Manual" rule).
      * Windsurf — ``trigger: always_on`` applies the rule universally.
    Agents without dedicated front-matter return ``""``.
    """
    desc = "Read this project's architecture via the Bounds CLI, not the raw files"
    front = {
        "claude": f"---\ndescription: {desc}\n---\n",
        "cursor": f"---\ndescription: {desc}\nalwaysApply: true\n---\n",
        "windsurf": f"---\ntrigger: always_on\ndescription: {desc}\n---\n",
    }
    return front.get(agent.key, "")


def _dedicated_body(agent: "_Agent") -> str:
    """Inner body for a dedicated (bounds-only) file's managed block.

    Claude's file is a real slash command, so it forwards ``$ARGUMENTS`` to the CLI: running
    ``/bounds describe auth`` actually executes ``bounds describe auth`` (and a bare ``/bounds``
    falls back to ``bounds overview -H``). The CLI keeps space-separated subcommands — we never
    rename a command or hyphenate it. Cursor/Windsurf get the short shared pointer body (they
    are passive always-on rules, not invokable commands).
    """
    if agent.key == "claude":
        return _CLAUDE_COMMAND_BODY
    return "# Bounds\n\n" + _AGENT_POINTER_BODY


# The Claude slash-command body. A thin pointer that *forwards* arguments to the CLI so the
# command is actually runnable, with a short usage list. `$ARGUMENTS` is Claude Code's verbatim
# substitution of whatever follows `/bounds`; empty args default to the overview.
_CLAUDE_COMMAND_BODY = """\
# /bounds

Run the **Bounds** CLI to read this project's architecture (subsystem boundaries, public
surfaces, drift) — never read the raw source or `.bounds/` files. Output is JSON by default;
add `-H` for human-readable.

Run:

```
bounds $ARGUMENTS
```

If no arguments were given, show the map instead:

```
bounds overview -H
```

Usage — `/bounds <subcommand> [args]` forwards verbatim to `bounds <subcommand> [args]`:
- `/bounds list` — all subsystems (roles + dependency counts)
- `/bounds describe <name>` — one subsystem's verified public surface (a few hundred tokens for a small subsystem)
- `/bounds describe --namespace <ns>` — every subsystem in a namespace
- `/bounds validate --quick` — catch drift after a change
- `/bounds impact <name>` — transitive blast radius before a risky change
- `/bounds overview -H` — project health at a glance

Never read `.bounds/cache.db`, `.bounds/*.json`, or `.bounds/manifests/*.yaml` directly — the
cache is binary and the manifests bypass tree-sitter verification. The CLI is the API. See
`AGENTS.md` for the full contract.
"""


def _pointer_block_body(fmt: str) -> str:
    """The inner body (no markers) for a shared *pointer* file in the requested format."""
    if fmt == _YAML:
        return "\n".join(
            [
                "# Bounds models this codebase as subsystem boundary manifests.",
                "# Read architecture via the CLI, never the raw files:",
                "#   bounds list / bounds describe <name> / bounds validate --quick",
                "# Never read .bounds/cache.db, .bounds/*.json, or .bounds/manifests/*.yaml.",
                "# The CLI is the API. See AGENTS.md for the full contract.",
                "read: [AGENTS.md]",
            ]
        )
    return "## Bounds\n\n" + _AGENT_POINTER_BODY.rstrip("\n")


# ---------------------------------------------------------------------------
# mode = sync
# ---------------------------------------------------------------------------
def _sync(root: Path, selected: list[str]) -> dict:
    """Write the canonical ``AGENTS.md`` and the selected agents' pointer files.

    ``AGENTS.md`` is always (re)written first — it is the source of truth every pointer
    references — then each selected agent that has its *own* file gets a marked, stamped block.
    Codex/OpenCode are satisfied by ``AGENTS.md`` itself, so selecting them is a no-op beyond
    the canonical write.

    Every file is marker-managed: content *outside* the markers (including a dedicated file's
    front-matter and any human additions) is preserved byte-for-byte, and only the block inside
    the markers is refreshed. If a file's in-marker body was hand-edited since we last stamped
    it (its content no longer matches the recorded hash), it is reported ``skipped_custom`` and
    left untouched rather than clobbered.

    Returns sorted, POSIX-relative ``created`` / ``updated`` / ``skipped_custom`` path lists
    plus ``canonical`` (always ``"AGENTS.md"``).
    """
    created: set[str] = set()
    updated: set[str] = set()
    skipped: set[str] = set()

    # 1. Canonical AGENTS.md — always written, as a marked block so any other AGENTS.md
    #    content the project keeps is preserved.
    canonical_path = root / CANONICAL_NAME
    rel_canonical = CANONICAL_NAME
    outcome = _upsert_block(canonical_path, _MARKDOWN, CANONICAL_BODY.rstrip("\n"))
    _record(outcome, rel_canonical, created, updated, skipped)

    # 2. Per-tool files for the selected agents (AGENTS.md already handled above).
    done: set[str] = {CANONICAL_NAME}
    for key in selected:
        agent = _AGENTS[key]
        if agent.canonical or agent.path in done:
            continue  # covered by the canonical AGENTS.md write
        done.add(agent.path)
        outcome = _upsert_block(
            root / Path(agent.path), agent.fmt, _expected_body(agent), prefix=_front_matter(agent)
        )
        _record(outcome, Path(agent.path).as_posix(), created, updated, skipped)

    return {
        "created": sorted(created),
        "updated": sorted(updated),
        "skipped_custom": sorted(skipped),
        "canonical": rel_canonical,
    }


def _record(outcome: str, rel: str, created: set, updated: set, skipped: set) -> None:
    """Bucket a write outcome into the right report set (``unchanged`` reports nothing)."""
    if outcome == "created":
        created.add(rel)
    elif outcome == "updated":
        updated.add(rel)
    elif outcome == "skipped_custom":
        skipped.add(rel)


def _upsert_block(target: Path, fmt: str, body: str, prefix: str = "") -> str:
    """Insert or refresh our marked+stamped block in ``target``, preserving other content.

    ``body`` is the inner content (no markers); this wraps it via :func:`_build_block`.
    ``prefix`` is content that must lead the file when we *create* it (a dedicated file's
    front-matter); on an existing file the prefix is left to whatever the file already has.

    Returns:
        ``created``        — file did not exist; created with ``prefix`` + our block.
        ``updated``        — our marked block was inserted into / refreshed in an existing file.
        ``unchanged``      — file already contained an identical marked block.
        ``skipped_custom`` — the existing block's body was hand-edited (hash mismatch), or the
                             file mentions bounds but has no markers at all. Left untouched.
    """
    start, end = (_YAML_START, _YAML_END) if fmt == _YAML else (_MD_START, _MD_END)
    block = _build_block(fmt, body)

    if not target.exists():
        _write_text(target, (prefix + "\n" if prefix else "") + block + "\n")
        return "created"

    existing = _read_text(target)

    if start in existing and end in existing:
        current_inner = _extract_inner(existing, start, end)
        if current_inner is not None and _is_hand_edited(current_inner, fmt):
            return "skipped_custom"  # human edited inside the markers — never clobber.
        new = _replace_block(existing, start, end, block)
        if new == existing:
            return "unchanged"
        _write_text(target, new)
        return "updated"

    # No markers. If the file already talks about bounds, a human wrote it — don't clobber.
    if _looks_bounds_authored(existing):
        return "skipped_custom"

    # Unrelated content with no markers: append our block, preserving theirs.
    sep = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    _write_text(target, existing + sep + block + "\n")
    return "updated"


def _extract_inner(text: str, start: str, end: str) -> str | None:
    """Return the content between the first ``start`` and ``end`` markers (exclusive), or None.

    The returned text is the *raw* in-marker block, stamp line included; callers strip the
    stamp themselves when they need the body alone.
    """
    i = text.find(start)
    if i == -1:
        return None
    j = text.find(end, i + len(start))
    if j == -1:
        return None
    return text[i + len(start):j].strip("\n")


def _split_stamp(inner: str, fmt: str) -> tuple[str | None, str | None, str]:
    """Split a raw in-marker block into ``(version, hash, body)``.

    The stamp is the first line when present; ``version``/``hash`` are None for a legacy
    (un-stamped) block, with the whole text returned as the body.
    """
    pattern = _YAML_STAMP_RE if fmt == _YAML else _MD_STAMP_RE
    lines = inner.split("\n")
    if lines:
        m = pattern.fullmatch(lines[0].strip())
        if m:
            return m.group("v"), m.group("h"), "\n".join(lines[1:]).strip("\n")
    return None, None, inner


def _is_hand_edited(inner: str, fmt: str) -> bool:
    """True when an existing in-marker block was edited by a human since we stamped it.

    A block we wrote carries a stamp whose hash matches its body. If the recorded hash and the
    body's actual hash disagree, a human touched the content — refuse to clobber it. A legacy
    block with no stamp at all is treated as ours (we wrote it before stamping existed), so it
    is safe to refresh.
    """
    _v, recorded, body = _split_stamp(inner, fmt)
    if recorded is None:
        return False  # legacy un-stamped block we authored — safe to refresh.
    return _body_hash(body) != recorded


def _replace_block(text: str, start: str, end: str, block: str) -> str:
    """Replace the first ``start``…``end`` marked region (inclusive) with ``block``.

    Operates on the raw text so surrounding content — before the start marker and after the
    end marker — is preserved byte-for-byte.
    """
    i = text.index(start)
    j = text.index(end, i) + len(end)
    return text[:i] + block + text[j:]


_BOUNDS_COMMAND_RE = re.compile(
    r"\bbounds\s+"
    r"(list|describe|validate|preflight|overview|init|impact|discover|calibrate|agent|ci|cache)\b"
)
_BOUNDS_HEADING_RE = re.compile(r"(?m)^\s*#.*\bbounds\b")


def _looks_bounds_authored(text: str) -> bool:
    """Heuristic: does an unmarked shared file already contain hand-written bounds content?

    Used only to decide ``skipped_custom``. We look for unambiguous signals that a human wrote
    bounds guidance, so we err toward *not* clobbering:
      * a real CLI invocation — the word ``bounds`` immediately followed by a known subcommand;
      * the inline-code form ```` `bounds` ````;
      * a markdown heading line that names Bounds.

    Critically, plain English prose such as "out of bounds" or "bounds checking" must NOT
    match — those are safe to append our block to. Returns False for any such unrelated content.
    """
    lowered = text.lower()
    return (
        bool(_BOUNDS_COMMAND_RE.search(lowered))
        or "`bounds`" in lowered
        or bool(_BOUNDS_HEADING_RE.search(lowered))
    )


# ---------------------------------------------------------------------------
# mode = detect
# ---------------------------------------------------------------------------
def _detect(root: Path) -> dict:
    """Heuristically report which agents' tool footprints are present in ``root``.

    Heuristic (presence of the agent's native footprint, independent of whether bounds has
    been synced yet):
      * claude   — ``.claude/`` directory exists.
      * codex    — ``AGENTS.md`` exists (Codex's instruction file).
      * opencode — ``AGENTS.md`` exists (OpenCode shares the same file).
      * gemini   — ``GEMINI.md`` exists.
      * copilot  — ``.github/copilot-instructions.md`` exists (its actual instruction file — a
        bare ``.github/`` directory is universal and not a Copilot signal).
      * cursor   — ``.cursor/`` directory exists.
      * aider    — ``.aider.conf.yml`` exists.
      * windsurf — ``.windsurf/`` directory exists.

    Returns ``{"detected": [sorted agent keys]}``.
    """
    detected = [k for k in AGENT_KEYS if _footprint_present(root, k)]
    return {"detected": sorted(detected)}


def _footprint_present(root: Path, key: str) -> bool:
    """True when ``key``'s native tool footprint exists under ``root`` (see :func:`_detect`)."""
    checks = {
        "claude": (root / ".claude").is_dir,
        "codex": (root / CANONICAL_NAME).is_file,
        "opencode": (root / CANONICAL_NAME).is_file,
        "gemini": (root / "GEMINI.md").is_file,
        "copilot": (root / ".github" / "copilot-instructions.md").is_file,
        "cursor": (root / ".cursor").is_dir,
        "aider": (root / ".aider.conf.yml").is_file,
        "windsurf": (root / ".windsurf").is_dir,
    }
    return checks[key]()


# ---------------------------------------------------------------------------
# mode = check
# ---------------------------------------------------------------------------
def _check(root: Path, selected: list[str]) -> dict:
    """Report, for each detected-and-selected agent, whether its bounds config is up to date.

    We intersect with detection so a check reports only on agents actually in use — selecting
    all eight on a Claude-only repo won't flag cursor/gemini/etc. We classify each target as:

      * ``missing``    — the config file doesn't exist, or exists but carries no bounds block
                         (no markers / never synced).
      * ``stale``      — a bounds block is present but its stamped version+hash no longer match
                         what the installed CLI would generate (the contract moved on, or the
                         file was synced by an older bounds). Refresh with ``bounds agent --sync``.
      * ``configured`` — a bounds block is present and its stamp matches the current expected
                         body exactly.

    Returns ``{"ok": bool, "missing": [...], "stale": [...], "configured": [...], "fix": "..."}``
    with sorted key lists; ``ok`` is True iff nothing is missing *and* nothing is stale. The
    ``fix`` field is only present when there is something to fix.
    """
    detected = set(_detect(root)["detected"])
    targets = [k for k in selected if k in detected]

    configured: list[str] = []
    missing: list[str] = []
    stale: list[str] = []
    for key in targets:
        status = _config_status(root, _AGENTS[key])
        if status == "missing":
            missing.append(key)
        elif status == "stale":
            stale.append(key)
        else:
            configured.append(key)

    result: dict = {
        "ok": not missing and not stale,
        "missing": sorted(missing),
        "stale": sorted(stale),
        "configured": sorted(configured),
    }
    if missing or stale:
        result["fix"] = "bounds agent --sync"
    return result


def _config_status(root: Path, agent: "_Agent") -> str:
    """Classify ``agent``'s config file as ``missing`` / ``stale`` / ``configured``.

    "Up to date" means the file has our markers AND the in-marker block carries a stamp whose
    version+hash exactly match what the installed CLI would generate for that file right now.
    A present-but-un-stamped block, a present block stamped by an older version, or a present
    block whose body was hand-edited all read as ``stale`` — so a synced file overwritten with
    garbage no longer falsely reports ok.
    """
    target = root / Path(agent.path)
    if not target.exists():
        return "missing"

    start = _YAML_START if agent.fmt == _YAML else _MD_START
    end = _YAML_END if agent.fmt == _YAML else _MD_END
    text = _read_text(target)
    if start not in text or end not in text:
        return "missing"  # file exists but was never synced (no bounds block).

    inner = _extract_inner(text, start, end)
    if inner is None:
        return "missing"
    version, recorded, body = _split_stamp(inner, agent.fmt)

    expected_body = _expected_body(agent)
    expected_hash = _body_hash(expected_body)
    # Stale if: never stamped, stamped by a different version, the recorded hash doesn't match
    # the current expected body, or the on-disk body itself drifted from its own stamp.
    if recorded is None or version != _version() or recorded != expected_hash:
        return "stale"
    if _body_hash(body) != recorded:
        return "stale"
    return "configured"


# ---------------------------------------------------------------------------
# Filesystem helpers (centralized so encoding/newlines stay consistent)
# ---------------------------------------------------------------------------
def _read_text(path: Path) -> str:
    """Read a file as UTF-8 text (no surprises across platforms)."""
    return path.read_text(encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    """Write UTF-8 text, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
