"""Project-specific exclusion (`.boundsignore`) and generated-code detection.

Two deterministic, zero-LLM concerns live here:

* **`.boundsignore`** — a git-committable list of glob patterns that exclude files
  from analysis. Loaded from ``.boundsignore`` (project root) or ``.bounds/ignore``,
  plus an optional gitignored ``.boundsignore.local`` for personal overrides. The legacy
  ``.compactignore`` / ``.compact/ignore`` names are still read for backward
  compatibility. Patterns use ``.gitignore``-style globs and are matched against
  repo-relative POSIX paths. A match overrides a subsystem's ``paths``/``files``
  ownership — an ignored file is never extracted, unless the caller forces re-inclusion
  (``--include-ignored``).

* **Generated code** — files carrying a ``@generated`` / ``auto-generated`` header
  marker, or matching a subsystem's ``generated`` globs, are flagged ``generated: true``
  in output. They are still extracted — kept visible, just labelled.

Everything is pure ``pathlib`` + ``re``; patterns compile to anchored regexes once.
No timestamps, randomness, or set-ordering leaks into any result.
"""

from __future__ import annotations

import re
from pathlib import Path

from . import config

# Header markers that identify auto-generated source (case-insensitive). Only the first slice of the
# file is inspected (head-only scan) so a passing mention deep in a body never trips — that head-only
# window is the false-positive guard, so it is deliberately not widened. Beyond the original
# decorator-style markers, the compiled-language tokens catch the most common generated headers in
# languages Bounds has no adapter for — the Go protobuf ``protoc-gen-go`` banner and gRPC/Thrift/SWIG
# stubs all carry one — so a generated compiled file is recognized as generated (excluded from
# coverage, never proposed as an expose). The compiled-language tokens are assembled from fragments
# rather than spelled out literally: this module is itself analysable source, so a verbatim header
# phrase here would self-misdetect THIS file as generated (the same self-protection calibrate's
# header comment uses). The runtime tuple is the full phrase; the source text never is.
_GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "@auto-generated",
    "@generated " + "by",
    "do " + "not " + "edit",
    "code " + "generated " + "by",
)
_GENERATED_SCAN_BYTES = 4096

# Candidate locations for the ignore file, in load order. Committed first, personal last.
# Legacy ``.compact*`` names (including the personal ``.compactignore.local``) are kept
# for backward compatibility so a mid-migration repo never silently loses exclusions.
_IGNORE_FILES = (
    ".boundsignore",
    f"{config.BOUNDS_DIR}/ignore",
    ".compactignore",
    f"{config.LEGACY_DIR}/ignore",
    ".boundsignore.local",
    ".compactignore.local",
)


# ---------------------------------------------------------------------------
# .boundsignore loading + matching
# ---------------------------------------------------------------------------
def load_ignore_patterns(project_root: Path) -> list[str]:
    """Return the ordered, de-commented patterns from every present ignore file.

    Reads each candidate in :data:`_IGNORE_FILES` that exists, dropping blank lines and
    ``#`` comments. Missing or unreadable files contribute nothing (fail soft). Order is
    deterministic (file order, then line order); duplicates are preserved harmlessly.
    """
    patterns: list[str] = []
    for rel in _IGNORE_FILES:
        path = project_root / rel
        try:
            if not path.is_file():
                continue
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            patterns.append(line)
    return patterns


def _compile_pattern(pattern: str) -> re.Pattern[str]:
    """Translate one ``.gitignore``-style glob into an anchored regex.

    Supported: ``**`` (any number of path segments, including zero), ``*`` (any run of
    non-``/`` chars), ``?`` (one non-``/`` char). A trailing ``/`` (directory pattern)
    matches the directory and everything beneath it. A leading ``/`` anchors to the root;
    otherwise the pattern still matches from the root (wildcards are relative to the
    project root). A pattern with no wildcard also matches everything beneath it, so
    ``vendor`` excludes ``vendor/a/b.py`` just like ``vendor/**`` does.
    """
    pat = pattern.strip()
    pat = pat[1:] if pat.startswith("/") else pat
    trailing_dir = pat.endswith("/")
    pat = pat.rstrip("/")

    has_wildcard = any(ch in pat for ch in "*?[")
    out: list[str] = []
    i = 0
    n = len(pat)
    while i < n:
        ch = pat[i]
        if ch == "*":
            if pat[i : i + 2] == "**":
                # Collapse "**/" -> optional segments; bare "**" -> anything.
                if pat[i : i + 3] == "**/":
                    out.append("(?:.*/)?")
                    i += 3
                    continue
                out.append(".*")
                i += 2
                continue
            out.append("[^/]*")
            i += 1
        elif ch == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(ch))
            i += 1

    body = "".join(out)
    if trailing_dir or not has_wildcard:
        # Directory / plain-name pattern: match the path itself or anything under it.
        regex = rf"^{body}(?:/.*)?$"
    else:
        regex = rf"^{body}$"
    return re.compile(regex)


class IgnoreMatcher:
    """Compiled ``.boundsignore`` matcher over repo-relative POSIX paths."""

    def __init__(self, patterns: list[str]) -> None:
        self.patterns = list(patterns)
        self._regexes = [_compile_pattern(p) for p in patterns]

    def __bool__(self) -> bool:
        return bool(self._regexes)

    def matches(self, rel_posix: str) -> bool:
        """True if ``rel_posix`` matches any ignore pattern."""
        return any(rx.match(rel_posix) for rx in self._regexes)


def load_matcher(project_root: Path) -> IgnoreMatcher:
    """Build an :class:`IgnoreMatcher` from the project's ignore files."""
    return IgnoreMatcher(load_ignore_patterns(project_root))


# ---------------------------------------------------------------------------
# Generated-code detection
# ---------------------------------------------------------------------------
def has_generated_marker(source: bytes) -> bool:
    """True if the file's header carries a recognized generated-code marker.

    Only the first :data:`_GENERATED_SCAN_BYTES` bytes are inspected (markers live in
    file headers); matching is case-insensitive and byte-safe.
    """
    head = source[:_GENERATED_SCAN_BYTES].lower()
    return any(marker.encode("ascii") in head for marker in _GENERATED_MARKERS)


def is_generated(rel_posix: str, source: bytes | None, generated_globs: list[str]) -> bool:
    """Decide whether a file is generated, by ``generated`` glob or by header marker.

    ``generated_globs`` are matched with the same ``.gitignore``-style semantics as
    ``.boundsignore``. ``source`` may be ``None`` when only the glob test is wanted.
    """
    for glob in generated_globs:
        if _compile_pattern(glob).match(rel_posix):
            return True
    if source is not None and has_generated_marker(source):
        return True
    return False
